/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4_juiceshopmanagement.view;

import g4_juiceshopmanagement.controller.InvoiceDAO;
import g4_juiceshopmanagement.controller.InvoiceDetailsDAO;
import g4_juiceshopmanagement.model.CustomTableRenderer;
import g4_juiceshopmanagement.model.Invoice;
import g4_juiceshopmanagement.model.InvoiceDetails;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahuy96
 */
public class InvoiceFrm extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceFrm
     */
    public InvoiceFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadInvoiceTable();
        lbl_inoice_total.setText("");
        lbl_invoice_id.setText("");
        lbl_invoice_issuedDate.setText("");
    }

    private void loadInvoiceTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_invoice_invoice.getModel();
        InvoiceDAO invoiceDAO = new InvoiceDAO();
        ArrayList<Invoice> invoiceList = invoiceDAO.getAll();
        int count = model.getRowCount();
        while (count > 0) {
            model.removeRow(count - 1);
            count--;
        }
        for (Invoice invoice : invoiceList) {
            Object[] row = {
                invoice.getID(),
                invoice.getIssuedDate(),
                invoice.getTotal()
            };
            model.addRow(row);
        }

    }

    private void loadInvoiceDetailsTable(int invoiceID) {
        DefaultTableModel model = (DefaultTableModel) tbl_invoice_invoiceDetails.getModel();
        InvoiceDetailsDAO invoiceDetailsDAO = new InvoiceDetailsDAO();
        ArrayList<InvoiceDetails> invoiceDetailsList = invoiceDetailsDAO.getByInvoiceID(invoiceID);

        int count = model.getRowCount();
        while (count > 0) {
            model.removeRow(count - 1);
            count--;
        }
        for (InvoiceDetails invoiceDetails : invoiceDetailsList) {
            JLabel jlabel = new JLabel();
            jlabel.setIcon(invoiceDetails.getProduct().getImg());
            Object[] row = {
                //                new ImageIcon(System.getProperty("user.dir") + "\\Images\\" + invoiceDetails.getProduct().getName() + ".png"),
                jlabel,
                invoiceDetails.getProduct().getName() + " " + invoiceDetails.getProduct().getCategory().getName(),
                invoiceDetails.getQuantity(),
                invoiceDetails.getPrice(),};
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_invoice_invoice = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_invoice_invoiceDetails = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_invoice_issuedDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_invoice_id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_inoice_total = new javax.swing.JLabel();
        btn_invoice_goBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Invoice Management");

        tbl_invoice_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Issued date", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_invoice_invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_invoice_invoiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_invoice_invoice);

        tbl_invoice_invoiceDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Image", "Name", "Quantity", "Sum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_invoice_invoiceDetails.getColumn("Image").setCellRenderer(new CustomTableRenderer());
        jScrollPane2.setViewportView(tbl_invoice_invoiceDetails);

        jLabel2.setText("Invoice Details: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Issued date: ");

        lbl_invoice_issuedDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_invoice_issuedDate.setForeground(new java.awt.Color(51, 153, 255));
        lbl_invoice_issuedDate.setText("issuedDate");

        jLabel4.setText("Order No.");

        lbl_invoice_id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_invoice_id.setForeground(new java.awt.Color(255, 0, 102));
        lbl_invoice_id.setText("No.");

        jLabel6.setText("Total: ");

        lbl_inoice_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_inoice_total.setForeground(new java.awt.Color(0, 51, 204));
        lbl_inoice_total.setText("Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_invoice_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_inoice_total)
                    .addComponent(lbl_invoice_issuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_invoice_issuedDate)
                    .addComponent(jLabel4)
                    .addComponent(lbl_invoice_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_inoice_total))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_invoice_goBack.setText("Go back");
        btn_invoice_goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invoice_goBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_invoice_goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_invoice_goBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_invoice_invoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_invoice_invoiceMouseClicked
        // TODO add your handling code here:
        int index = tbl_invoice_invoice.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl_invoice_invoice.getModel();
        int invoiceID = (int) model.getValueAt(index, 0);
        loadInvoiceDetailsTable(invoiceID);
        lbl_invoice_id.setText(String.valueOf(invoiceID));
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String dob = sdf.format(model.getValueAt(index, 1));
            lbl_invoice_issuedDate.setText(dob);
        } catch (Exception e) {
        }

        lbl_inoice_total.setText(String.valueOf(model.getValueAt(index, 2)));

    }//GEN-LAST:event_tbl_invoice_invoiceMouseClicked

    private void btn_invoice_goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invoice_goBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_invoice_goBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_invoice_goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_inoice_total;
    private javax.swing.JLabel lbl_invoice_id;
    private javax.swing.JLabel lbl_invoice_issuedDate;
    private javax.swing.JTable tbl_invoice_invoice;
    private javax.swing.JTable tbl_invoice_invoiceDetails;
    // End of variables declaration//GEN-END:variables
}
