/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4_juiceshopmanagement.view;

import g4_juiceshopmanagement.model.Account;

/**
 *
 * @author ahuy96
 */
public class MainFrm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrm
     */
    public MainFrm(Account account) {
        initComponents();
        lbl_user.setText("Welcome: "+account.getFullName());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_user = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menu_product = new javax.swing.JMenuItem();
        menu_category = new javax.swing.JMenuItem();
        menu_customer = new javax.swing.JMenuItem();
        menu_staff = new javax.swing.JMenuItem();
        menu_invoice = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(102, 153, 255));
        lbl_user.setText("lblUser");

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g4_juiceshopmanagement/view/Images/shreklogo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Shrek Juice Shop Management");

        jMenu2.setText("Management");

        menu_product.setText("Products");
        menu_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_productActionPerformed(evt);
            }
        });
        jMenu2.add(menu_product);

        menu_category.setText("Categories");
        menu_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_categoryActionPerformed(evt);
            }
        });
        jMenu2.add(menu_category);

        menu_customer.setText("Customer");
        menu_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_customerActionPerformed(evt);
            }
        });
        jMenu2.add(menu_customer);

        menu_staff.setText("Staff");
        menu_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_staffActionPerformed(evt);
            }
        });
        jMenu2.add(menu_staff);

        menu_invoice.setText("Invoice");
        menu_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_invoiceActionPerformed(evt);
            }
        });
        jMenu2.add(menu_invoice);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 232, Short.MAX_VALUE)
                        .addComponent(lbl_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_logout)
                            .addComponent(lbl_user))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_categoryActionPerformed
        // TODO add your handling code here:
        CategoryFrm categoryFrm = new CategoryFrm();
        categoryFrm.setVisible(true);

    }//GEN-LAST:event_menu_categoryActionPerformed

    private void menu_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_productActionPerformed
        // TODO add your handling code here:
        ProductFrm productFrm = new ProductFrm();
        productFrm.setVisible(true);

    }//GEN-LAST:event_menu_productActionPerformed

    private void menu_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_customerActionPerformed
        // TODO add your handling code here:
        CustomerFrm customerFrm = new CustomerFrm();
        customerFrm.setVisible(true);
    }//GEN-LAST:event_menu_customerActionPerformed

    private void menu_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_staffActionPerformed
        // TODO add your handling code here:
        StaffFrm staffFrm = new StaffFrm();
        staffFrm.setVisible(true);

    }//GEN-LAST:event_menu_staffActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        LoginFrm loginFrm = new LoginFrm();
        loginFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void menu_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_invoiceActionPerformed
        // TODO add your handling code here:
        InvoiceFrm invoiceFrm = new InvoiceFrm();
        invoiceFrm.setVisible(true);
    }//GEN-LAST:event_menu_invoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new MainFrm(new Account()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JMenuItem menu_category;
    private javax.swing.JMenuItem menu_customer;
    private javax.swing.JMenuItem menu_invoice;
    private javax.swing.JMenuItem menu_product;
    private javax.swing.JMenuItem menu_staff;
    // End of variables declaration//GEN-END:variables
}
