/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4_juiceshopmanagement.view;

import g4_juiceshopmanagement.controller.CategoryDAO;
import g4_juiceshopmanagement.controller.InvoiceDAO;
import g4_juiceshopmanagement.controller.InvoiceDetailsDAO;
import g4_juiceshopmanagement.controller.ProductDAO;
import g4_juiceshopmanagement.model.Account;
import g4_juiceshopmanagement.model.Cart;
import g4_juiceshopmanagement.model.Category;
import g4_juiceshopmanagement.model.CustomRenderer;
import g4_juiceshopmanagement.model.Invoice;
import g4_juiceshopmanagement.model.InvoiceDetails;
import g4_juiceshopmanagement.model.MenuItem;
import g4_juiceshopmanagement.model.Product;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahuy96
 */
public class PurchaseFrm extends javax.swing.JFrame {

    private Account user;

    public void setUser(Account user) {
        this.user = user;
    }

    public Account getUser() {
        return user;
    }

    /**
     * Creates new form PurchaseFrm
     */
    public PurchaseFrm() {

    }

    public PurchaseFrm(Account account) {

        initComponents();
        tb_cart.removeColumn(tb_cart.getColumnModel().getColumn(3));
        createProductMenu();
        this.setUser(account);
        lbl_purchase_user.setText("Hello: " + account.getUsername());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbp_menu = new javax.swing.JTabbedPane();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lbl_proName = new javax.swing.JLabel();
        sp_proQuantity = new javax.swing.JSpinner();
        lbl_proPrice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_proTotal = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_cart = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lbl_proImg = new javax.swing.JLabel();
        btn_addCart = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_proIngredient = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_proDes = new javax.swing.JTextArea();
        lbl_proID = new javax.swing.JLabel();
        btn_deleteCart = new javax.swing.JButton();
        btn_cartUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_cartTotal = new javax.swing.JLabel();
        btn_checkOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_purchase_user = new javax.swing.JLabel();
        btn_purchase_user = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_proName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proName.setForeground(new java.awt.Color(255, 102, 102));
        lbl_proName.setText("Product name");

        sp_proQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        sp_proQuantity.setValue(1);
        sp_proQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sp_proQuantityStateChanged(evt);
            }
        });

        lbl_proPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_proPrice.setForeground(new java.awt.Color(51, 102, 255));
        lbl_proPrice.setText("Price");

        jLabel3.setText("Total:");

        lbl_proTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_proTotal.setForeground(new java.awt.Color(255, 0, 51));
        lbl_proTotal.setText("$0");

        tb_cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Sum", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_cartMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_cart);

        jLabel4.setText("Quantity: ");

        lbl_proImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_addCart.setText("Add to cart");
        btn_addCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addCartActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Description: ");

        jLabel7.setText("Ingredient: ");

        txt_proIngredient.setEditable(false);
        txt_proIngredient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_proDes.setEditable(false);
        txt_proDes.setColumns(20);
        txt_proDes.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txt_proDes.setLineWrap(true);
        txt_proDes.setRows(5);
        jScrollPane1.setViewportView(txt_proDes);

        lbl_proID.setText("proID");
        lbl_proID.setEnabled(false);
        lbl_proID.setFocusable(false);
        lbl_proID.setVisible(false);

        btn_deleteCart.setText("Delete item");
        btn_deleteCart.setEnabled(false);
        btn_deleteCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteCartActionPerformed(evt);
            }
        });

        btn_cartUpdate.setText("Update cart");
        btn_cartUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cartUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lbl_proPrice))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_addCart, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cartUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_proTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp_proQuantity))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_proImg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_proName))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_proID)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_proIngredient)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_deleteCart)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_proIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                    .addComponent(lbl_proImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_proName)
                    .addComponent(lbl_proID))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_proQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_proPrice)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cartUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_proTotal)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_addCart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_deleteCart)
                .addGap(13, 13, 13))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Total");

        lbl_cartTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_cartTotal.setForeground(new java.awt.Color(51, 51, 255));
        lbl_cartTotal.setText("$0");

        btn_checkOut.setText("Check Out");
        btn_checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cartTotal)
                .addGap(56, 56, 56))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cartTotal)
                    .addComponent(btn_checkOut, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Welcome to our Juice Shop");

        lbl_purchase_user.setText("Hello: ");

        btn_purchase_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g4_juiceshopmanagement/view/Images/profle.png"))); // NOI18N
        btn_purchase_user.setBorder(null);
        btn_purchase_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_purchase_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_purchase_userActionPerformed(evt);
            }
        });

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbp_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_purchase_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_purchase_user)
                        .addGap(18, 18, 18)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(lbl_purchase_user))
                            .addComponent(btn_purchase_user))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbp_menu)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createList() {

    }

    public void createProductMenu() {
        PurchaseFrm pf = new PurchaseFrm();
        CategoryDAO cateDAO = new CategoryDAO();
        ProductDAO proDAO = new ProductDAO();
        java.util.ArrayList<Category> list = cateDAO.getAll();

        for (Category item : list) {
            DefaultListModel model = new DefaultListModel();
            java.util.ArrayList<Product> proList = proDAO.getByCategory(item.getiD());
            for (Product product : proList) {
//                MenuItem menuItem = new MenuItem();
//                menuItem.setId(product.getiD());
//                menuItem.setName(product.getName() + " " + item.getName());
//                menuItem.setImage(new ImageIcon(System.getProperty("user.dir") + "\\Images\\" + product.getName() + ".png"));
                product.setImg(new ImageIcon(System.getProperty("user.dir") + "\\Images\\" + product.getName() + ".png"));
//                model.addElement(menuItem);
                model.addElement(product);
            }
//            JList<MenuItem> list1 = new JList();
            JList<Product> list1 = new JList();
            list1.setCellRenderer(new CustomRenderer());
            list1.setModel(model);
            list1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    list1MouseClicked(evt, list1);
                }
            });

            tbp_menu.addTab(item.getName(), new JScrollPane(list1));

//            tbp_menu.addTab(item.getName(), new JList(model));
//            
//            jScrollPane1.setViewportView(jList1);
//            tbp_menu.addTab(item.getName(), new JScrollPane((new JList(model).setCellRenderer(CustomRenderer()))));
        }
    }

    private void btn_purchase_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_purchase_userActionPerformed
        // TODO add your handling code here:
        Account user = this.getUser();
        UserFrm userFrm = new UserFrm(user);
        userFrm.setVisible(true);
    }//GEN-LAST:event_btn_purchase_userActionPerformed

    private void sp_proQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sp_proQuantityStateChanged
        // TODO add your handling code here:
        try {
            float total = Float.parseFloat(lbl_proPrice.getText()) * (Integer) sp_proQuantity.getValue();
            lbl_proTotal.setText(String.valueOf(total));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_sp_proQuantityStateChanged
//    private static float cartTotal = 0;
    private static java.util.ArrayList<Cart> cartList = new java.util.ArrayList<Cart>();
    private void btn_addCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addCartActionPerformed
        // TODO add your handling code here:

        Cart cartItem = new Cart();
        boolean flag = false;
        for (Cart cart : cartList) {
            if (cart.getProductID() == Integer.parseInt(lbl_proID.getText())) {
//                int newQuantity = cart.getQuantity() + (int) sp_proQuantity.getValue();
                cart.setQuantity(cart.getQuantity() + (int) sp_proQuantity.getValue());
                cart.setTotal(cart.getTotal() + Float.parseFloat(lbl_proTotal.getText()));
                flag = true;
            }
        }
        if (!flag) {
            cartItem.setProductID(Integer.parseInt(lbl_proID.getText()));
            cartItem.setName(lbl_proName.getText());
            cartItem.setQuantity((int) sp_proQuantity.getValue());
            cartItem.setTotal(Float.parseFloat(lbl_proTotal.getText()));
            cartList.add(cartItem);
        }
        loadCartTable();

    }//GEN-LAST:event_btn_addCartActionPerformed

    private void loadCartTable() {
        float cartTotal = 0;
        DefaultTableModel model = (DefaultTableModel) tb_cart.getModel();
        int count = model.getRowCount();
        while (count > 0) {
            model.removeRow(count - 1);
            count--;
        }
        for (Cart cart : cartList) {
            Object[] row = {
                cart.getName(),
                cart.getQuantity(),
                cart.getTotal(),
                cart.getProductID()
            };
            model.addRow(row);
            cartTotal += cart.getTotal();
        }
        lbl_cartTotal.setText(String.valueOf(cartTotal));
        btn_deleteCart.setEnabled(false);
    }
    private void tb_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_cartMouseClicked
        // TODO add your handling code here:
        btn_deleteCart.setEnabled(true);
        btn_addCart.setEnabled(false);
        btn_cartUpdate.setEnabled(true);
        int index = tb_cart.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tb_cart.getModel();
        int proID = (int) model.getValueAt(index, 3);
        lbl_proID.setText(String.valueOf(proID));
        ProductDAO productDAO = new ProductDAO();
        Product product = productDAO.getByID(proID);
        for (Cart cart : cartList) {
            if (cart.getProductID() == proID) {
                sp_proQuantity.setValue(cart.getQuantity());
//                lbl_cartTotal.setText(String.valueOf(cart.getTotal()));
                break;
            }
        }
        lbl_proImg.setIcon(product.getImg());
        lbl_proName.setText(product.getName() + " " + product.getCategory().getName());
        txt_proDes.setText(product.getDescription());
        txt_proIngredient.setText(product.getIngredient());
        lbl_proPrice.setText(String.valueOf(product.getPrice()));
    }//GEN-LAST:event_tb_cartMouseClicked

    private void btn_cartUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cartUpdateActionPerformed
        // TODO add your handling code here:
        for (Cart cart : cartList) {
            if (cart.getProductID() == Integer.parseInt(lbl_proID.getText())) {
                cart.setQuantity((int) sp_proQuantity.getValue());
                cart.setTotal(Float.parseFloat(lbl_proTotal.getText()));
//                lbl_cartTotal.setText(String.valueOf(cart.getTotal()));
                break;
            }
        }
        loadCartTable();
    }//GEN-LAST:event_btn_cartUpdateActionPerformed

    private void btn_deleteCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteCartActionPerformed
        // TODO add your handling code here:
        int index = tb_cart.getSelectedRow();
        cartList.remove(index);
        loadCartTable();

    }//GEN-LAST:event_btn_deleteCartActionPerformed

    private void btn_checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkOutActionPerformed
        // TODO add your handling code here:

        InvoiceDAO invoiceDAO = new InvoiceDAO();

        PurchaseFrm pf = new PurchaseFrm();
        Invoice invoice = new Invoice();
        invoice.setAccountID(this.getUser().getID());
//        invoice.setAccountID(43);
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String issuedDate = sdf.format(new Date());
            invoice.setIssuedDate(sdf.parse(issuedDate));
        } catch (Exception e) {
        }
        invoice.setTotal(Float.parseFloat(lbl_cartTotal.getText()));
        if (invoiceDAO.add(invoice)) {
            InvoiceDetailsDAO invoiceDetailsDAO = new InvoiceDetailsDAO();
            InvoiceDetails invoiceDetails = new InvoiceDetails();
            int invoiceID = invoiceDAO.getNewestInvoiceID();
            for (Cart cart : cartList) {
                invoiceDetails.setInvoiceID(invoiceID);
                invoiceDetails.setProductID(cart.getProductID());
                invoiceDetails.setQuantity(cart.getQuantity());
                invoiceDetails.setPrice(cart.getTotal());
                if (!invoiceDetailsDAO.add(invoiceDetails)) {
                    JOptionPane.showMessageDialog(this, "failed!!!");
                }
            }
            cartList.removeAll(cartList);
            loadCartTable();
            JOptionPane.showMessageDialog(this, "Successful!!!");
        } else {
            JOptionPane.showMessageDialog(this, "failed!!!");
        }

    }//GEN-LAST:event_btn_checkOutActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginFrm lf = new LoginFrm();
        lf.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void list1MouseClicked(java.awt.event.MouseEvent evt, JList<Product> list) {
        // TODO add your handling code here:
        btn_addCart.setEnabled(true);
        btn_cartUpdate.setEnabled(false);
        int index = list.getSelectedIndex();
        System.out.println("Index Selected: " + index);
        System.out.println("ID Selected: " + list.getSelectedValue().getiD());
        String s = (String) list.getSelectedValue().getName();
        System.out.println("Value Selected: " + s);
        lbl_proID.setText(String.valueOf(list.getSelectedValue().getiD()));
        lbl_proName.setText(list.getSelectedValue().getName() + " " + list.getSelectedValue().getCategory().getName());
        txt_proDes.setText(list.getSelectedValue().getDescription());
        lbl_proPrice.setText(String.valueOf(list.getSelectedValue().getPrice()));
        txt_proIngredient.setText(list.getSelectedValue().getIngredient());
        lbl_proImg.setIcon(list.getSelectedValue().getImg());
        lbl_proTotal.setText(String.valueOf(list.getSelectedValue().getPrice() * (int) sp_proQuantity.getValue()));
        sp_proQuantity.setValue(1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseFrm(new Account()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addCart;
    private javax.swing.JButton btn_cartUpdate;
    private javax.swing.JButton btn_checkOut;
    private javax.swing.JButton btn_deleteCart;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_purchase_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_cartTotal;
    private javax.swing.JLabel lbl_proID;
    private javax.swing.JLabel lbl_proImg;
    private javax.swing.JLabel lbl_proName;
    private javax.swing.JLabel lbl_proPrice;
    private javax.swing.JLabel lbl_proTotal;
    private javax.swing.JLabel lbl_purchase_user;
    private javax.swing.JSpinner sp_proQuantity;
    private javax.swing.JTable tb_cart;
    private javax.swing.JTabbedPane tbp_menu;
    private javax.swing.JTextArea txt_proDes;
    private javax.swing.JTextField txt_proIngredient;
    // End of variables declaration//GEN-END:variables

    private static class ArrayList<T> {

        public ArrayList() {
        }
    }
}
