/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4_juiceshopmanagement.view;

import g4_juiceshopmanagement.controller.AccountDAO;
import g4_juiceshopmanagement.controller.StaffDAO;
import g4_juiceshopmanagement.model.Account;
import g4_juiceshopmanagement.model.Staff;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahuy96
 */
public class StaffFrm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFrm
     */
    public StaffFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_staff_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_staff_fullname = new javax.swing.JTextField();
        txt_staff_phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_staff_idCardNumber = new javax.swing.JTextField();
        btn_staff_add = new javax.swing.JButton();
        btn_staff_save = new javax.swing.JButton();
        btn_staff_update = new javax.swing.JButton();
        btn_staff_delete = new javax.swing.JButton();
        btn_staff_exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_staff_email = new javax.swing.JTextField();
        chkb_staff_isAdmin = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txt_staff_accountID = new javax.swing.JTextField();
        txt_staff_password = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Staff = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Staff Management");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer info: "));

        jLabel2.setText("Username: ");

        jLabel3.setText("Password: ");

        jLabel4.setText("Full name: ");

        jLabel5.setText("Email: ");

        jLabel6.setText("Phone: ");

        btn_staff_add.setText("Add");
        btn_staff_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staff_addActionPerformed(evt);
            }
        });

        btn_staff_save.setText("Save");
        btn_staff_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staff_saveActionPerformed(evt);
            }
        });

        btn_staff_update.setText("Update");
        btn_staff_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staff_updateActionPerformed(evt);
            }
        });

        btn_staff_delete.setText("Delete");
        btn_staff_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staff_deleteActionPerformed(evt);
            }
        });

        btn_staff_exit.setText("Exit");
        btn_staff_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staff_exitActionPerformed(evt);
            }
        });

        jLabel7.setText("ID Card number:");

        chkb_staff_isAdmin.setText("Is Admin");

        jLabel8.setText("AccountID:");

        txt_staff_accountID.setEditable(false);

        txt_staff_password.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn_staff_add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_staff_save, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_staff_update, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_staff_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_staff_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(txt_staff_password, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_staff_username, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_staff_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(49, 49, 49)
                                .addComponent(txt_staff_accountID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_staff_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txt_staff_idCardNumber)
                            .addComponent(txt_staff_email)
                            .addComponent(chkb_staff_isAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_staff_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_staff_accountID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_staff_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_staff_idCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkb_staff_isAdmin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_staff_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_staff_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_staff_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_staff_add)
                    .addComponent(btn_staff_save)
                    .addComponent(btn_staff_update)
                    .addComponent(btn_staff_delete)
                    .addComponent(btn_staff_exit))
                .addContainerGap())
        );

        tbl_Staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Fullname", "Email", "Phone", "ID Card Number", "IsAdmin", "Avatar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_StaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Staff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(278, 278, 278))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static boolean typeAction;

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tbl_Staff.getModel();
        StaffDAO staffDAO = new StaffDAO();
        ArrayList<Staff> list = staffDAO.getAll();
        int count = model.getRowCount();
        while (count > 0) {
            model.removeRow(count - 1);
            count--;
        }
        for (Staff item : list) {
            Object[] row = {
                item.getAccountID(),
                item.getAccount().getUsername(),
                item.getAccount().getPassword(),
                item.getAccount().getFullName(),
                item.getAccount().getEmail(),
                item.getAccount().getPhone(),
                item.getIDCardNumber(),
                item.isIsAdmin(),
                item.getAccount().getAvatar()
            };
            model.addRow(row);
        }
    }

    public void changeStatusButton(boolean value) {
        btn_staff_add.setEnabled(value);
        btn_staff_update.setEnabled(value);
        btn_staff_delete.setEnabled(value);
        btn_staff_save.setEnabled(!value);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_formWindowOpened

    private void resetForm(){
        txt_staff_username.setText("");
        txt_staff_password.setText("");
        txt_staff_fullname.setText("");
        txt_staff_email.setText("");
        txt_staff_idCardNumber.setText("");
        txt_staff_phone.setText("");
        txt_staff_accountID.setText("");
        chkb_staff_isAdmin.setSelected(false);
    }
    private void btn_staff_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staff_addActionPerformed
        // TODO add your handling code here:
        typeAction = true;
        resetForm();
        changeStatusButton(false);
    }//GEN-LAST:event_btn_staff_addActionPerformed

    private void btn_staff_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staff_saveActionPerformed
        // TODO add your handling code here:
        StaffDAO staffDAO = new StaffDAO();
        AccountDAO accountDAO = new AccountDAO();
        String username = txt_staff_username.getText();
        String password = txt_staff_password.getText();
        String fullname = txt_staff_fullname.getText();
        String email = txt_staff_email.getText();
        String phone = txt_staff_phone.getText();
        String idcard = txt_staff_idCardNumber.getText();
        boolean isAdmin = chkb_staff_isAdmin.isSelected();
        if (typeAction) {
            if (username.length() == 0 || password.length() == 0 || email.length() == 0) {
                JOptionPane.showMessageDialog(this, "Please enter full info!!!");
            } else if (accountDAO.isExist_Username(username)) {
                JOptionPane.showMessageDialog(this, "Username is existed!!!");
            } else {
                Account account = new Account();
                account.setUsername(username);
                account.setPassword(password);
                account.setFullName(fullname);
                account.setEmail(email);
                account.setPhone(phone);
                account.setAvatar(account.getUsername() + ".jpg");

                Staff staff = new Staff();
                staff.setAccountID(accountDAO.add(account));
                staff.setIDCardNumber(idcard);
                staff.setIsAdmin(isAdmin);
                if (staffDAO.add(staff)) {
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Add failed!!!");
                }
            }
            changeStatusButton(true);
        } else {
            if (username.length() == 0 || password.length() == 0 || email.length() == 0) {
                JOptionPane.showMessageDialog(this, "Please enter full info!!!");
            } else {
                Account account = new Account();
                account.setUsername(username);
                account.setPassword(password);
                account.setFullName(fullname);
                account.setEmail(email);
                account.setPhone(phone);
                account.setAvatar(account.getUsername() + ".jpg");
                account.setID(Integer.parseInt(txt_staff_accountID.getText()));
                if (accountDAO.update(account)) {
                    Staff staff = new Staff();
                    staff.setAccountID(account.getID());
                    staff.setIDCardNumber(idcard);
                    staff.setIsAdmin(isAdmin);
                    if (staffDAO.update(staff)) {
                        loadData();
                    } else {
                        JOptionPane.showMessageDialog(this, "Update failed!!!");
                    }
                }

            }
            changeStatusButton(true);
        }
        txt_staff_username.setText("");
        txt_staff_password.setText("");
        txt_staff_fullname.setText("");
        txt_staff_email.setText("");
        txt_staff_idCardNumber.setText("");
        txt_staff_phone.setText("");
        chkb_staff_isAdmin.setSelected(false);
    }//GEN-LAST:event_btn_staff_saveActionPerformed

    private void btn_staff_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staff_updateActionPerformed
        // TODO add your handling code here:
        typeAction = false;
        changeStatusButton(false);
    }//GEN-LAST:event_btn_staff_updateActionPerformed

    private void btn_staff_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staff_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_staff_exitActionPerformed

    private void tbl_StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_StaffMouseClicked
        // TODO add your handling code here:
        int index = tbl_Staff.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl_Staff.getModel();
        txt_staff_accountID.setText(String.valueOf(model.getValueAt(index, 0)));
        txt_staff_username.setText(String.valueOf(model.getValueAt(index, 1)));
        txt_staff_password.setText(String.valueOf(model.getValueAt(index, 2)));
        txt_staff_fullname.setText(String.valueOf(model.getValueAt(index, 3)));
        txt_staff_email.setText(String.valueOf(model.getValueAt(index, 4)));
        txt_staff_phone.setText(String.valueOf(model.getValueAt(index, 5)));
        txt_staff_idCardNumber.setText(String.valueOf(model.getValueAt(index, 6)));
        chkb_staff_isAdmin.setSelected((boolean) model.getValueAt(index, 7));
    }//GEN-LAST:event_tbl_StaffMouseClicked

    private void btn_staff_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staff_deleteActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Confirm delete?", "Warning", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            int accountID = Integer.parseInt(txt_staff_accountID.getText());
            StaffDAO staffDAO = new StaffDAO();
            AccountDAO accountDAO = new AccountDAO();
            if (staffDAO.delete(accountID)) {
                if (accountDAO.delete(accountID)) {
                    loadData();
                    resetForm();
                }                
            } else {
                JOptionPane.showMessageDialog(this, "Delete failed!!!");
            }
        }
    }//GEN-LAST:event_btn_staff_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_staff_add;
    private javax.swing.JButton btn_staff_delete;
    private javax.swing.JButton btn_staff_exit;
    private javax.swing.JButton btn_staff_save;
    private javax.swing.JButton btn_staff_update;
    private javax.swing.JCheckBox chkb_staff_isAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_Staff;
    private javax.swing.JTextField txt_staff_accountID;
    private javax.swing.JTextField txt_staff_email;
    private javax.swing.JTextField txt_staff_fullname;
    private javax.swing.JTextField txt_staff_idCardNumber;
    private javax.swing.JPasswordField txt_staff_password;
    private javax.swing.JTextField txt_staff_phone;
    private javax.swing.JTextField txt_staff_username;
    // End of variables declaration//GEN-END:variables
}
