/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4_juiceshopmanagement.view;

import g4_juiceshopmanagement.controller.AccountDAO;
import g4_juiceshopmanagement.controller.CustomerDAO;
import g4_juiceshopmanagement.controller.InvoiceDAO;
import g4_juiceshopmanagement.controller.InvoiceDetailsDAO;
import g4_juiceshopmanagement.model.Account;
import g4_juiceshopmanagement.model.CustomTableRenderer;
import g4_juiceshopmanagement.model.Customer;
import g4_juiceshopmanagement.model.Invoice;
import g4_juiceshopmanagement.model.InvoiceDetails;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ahuy96
 */
public class UserFrm extends javax.swing.JFrame {

    private Account user;
//    private Customer customer;
//
//    public Customer getCustomer() {
//        return customer;
//    }
//
//    public void setCustomer(Customer customer) {
//        this.customer = customer;
//    }

    public void setUser(Account user) {
        this.user = user;
    }

    public Account getUser() {
        return user;
    }

    /**
     * Creates new form UserFrm
     */
    public UserFrm(Account account) {
        this.setUser(account);
        initComponents();
        tbl_invoice.removeColumn(tbl_invoice.getColumnModel().getColumn(2));
        lbl_history_Date.setText("");
        lbl_history_no.setText("");
        lbl_history_total.setText("");
        this.setLocationRelativeTo(null);
        load(account);
        loadInvoiceTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageChooser = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_user_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_user_password = new javax.swing.JPasswordField();
        btn_user_changePassword = new javax.swing.JButton();
        btn_user_userpass_save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_user_confirmPassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_user_fullname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_user_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_user_phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_user_dob = new javax.swing.JTextField();
        lbl_user_avatar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_user_address = new javax.swing.JTextField();
        btn_user_save = new javax.swing.JButton();
        btn_user_chooseImg = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_invoice = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_invoiceDetails = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbl_history_no = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_history_Date = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_history_total = new javax.swing.JLabel();
        btn_user_goBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Username & Password"));

        jLabel1.setText("Username");

        txt_user_username.setEditable(false);

        jLabel2.setText("Password");

        txt_user_password.setEditable(false);

        btn_user_changePassword.setText("Change password");
        btn_user_changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_changePasswordActionPerformed(evt);
            }
        });

        btn_user_userpass_save.setText("Save");
        btn_user_userpass_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_userpass_saveActionPerformed(evt);
            }
        });

        jLabel3.setText("Confirm password");

        txt_user_confirmPassword.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_user_username)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txt_user_password)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_user_changePassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_user_userpass_save, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(txt_user_confirmPassword))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_user_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_user_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_user_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_user_changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_user_userpass_save, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("User info"));

        jLabel4.setText("Fullname");

        jLabel5.setText("Email");

        jLabel6.setText("Phone");

        jLabel7.setText("DoB");

        lbl_user_avatar.setBorder(javax.swing.BorderFactory.createTitledBorder("Avatar"));

        jLabel9.setText("Address");

        btn_user_save.setText("Save");
        btn_user_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_saveActionPerformed(evt);
            }
        });

        btn_user_chooseImg.setText("Choose image");
        btn_user_chooseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_chooseImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_user_phone)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_user_fullname)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_user_email, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_user_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_user_address, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_user_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_user_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_user_chooseImg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))))
                .addGap(70, 70, 70))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_user_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_user_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_user_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_user_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_user_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_user_chooseImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user_address, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_user_save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User info", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoice"));

        tbl_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Total", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_invoiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_invoice);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoice details"));

        tbl_invoiceDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Image", "Name", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_invoiceDetails.getColumn("Image").setCellRenderer(new CustomTableRenderer());
        jScrollPane2.setViewportView(tbl_invoiceDetails);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("No.");

        lbl_history_no.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_history_no.setForeground(new java.awt.Color(255, 0, 51));
        lbl_history_no.setText("No.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Date:");

        lbl_history_Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_history_Date.setForeground(new java.awt.Color(51, 51, 255));
        lbl_history_Date.setText("Date");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_history_no)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_history_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_history_no)
                    .addComponent(jLabel11)
                    .addComponent(lbl_history_Date))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Total: ");

        lbl_history_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_history_total.setForeground(new java.awt.Color(51, 51, 255));
        lbl_history_total.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_history_total, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lbl_history_total))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Purchase history", jPanel2);

        btn_user_goBack.setText("Go back");
        btn_user_goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_goBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_user_goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_user_goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadInvoiceTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_invoice.getModel();
        InvoiceDAO invoiceDAO = new InvoiceDAO();
        ArrayList<Invoice> invoiceList = invoiceDAO.getAllbyAccountID(this.getUser().getID());
//        ArrayList<Invoice> invoiceList = invoiceDAO.getAllbyAccountID(43);
        int count = model.getRowCount();
        while (count > 0) {
            model.removeRow(count - 1);
            count--;
        }
        for (Invoice invoice : invoiceList) {
            Object[] row = {
                invoice.getIssuedDate(),
                invoice.getTotal(),
                invoice.getID()
            };
            model.addRow(row);
        }

    }

    private void loadInvoiceDetailsTable(int invoiceID) {
        DefaultTableModel model = (DefaultTableModel) tbl_invoiceDetails.getModel();
        InvoiceDetailsDAO invoiceDetailsDAO = new InvoiceDetailsDAO();
        
        ArrayList<InvoiceDetails> invoiceDetailsList = invoiceDetailsDAO.getByInvoiceID(invoiceID);
        int count = model.getRowCount();
        while (count > 0) {
            model.removeRow(count - 1);
            count--;
        }
        int i = 0;
        for (InvoiceDetails invoiceDetails : invoiceDetailsList) {
            JLabel jlbl = new JLabel();
            jlbl.setIcon(invoiceDetails.getProduct().getImg());
            Object[] row = {
                //                new ImageIcon(System.getProperty("user.dir") + "\\Images\\" + invoiceDetails.getProduct().getName() + ".png"),
                jlbl,
                invoiceDetails.getProduct().getName() + " " + invoiceDetails.getProduct().getCategory().getName(),
                invoiceDetails.getQuantity(),
                invoiceDetails.getPrice(),};
            model.addRow(row);
            
            i++;
        }
//        tbl_invoiceDetails.getColumn("Image").setCellRenderer(new CustomTableRenderer());
    }



    private void load(Account account) {
        txt_user_username.setText(account.getUsername());
        txt_user_password.setText(account.getPassword());

        txt_user_fullname.setText(account.getFullName());
        txt_user_email.setText(account.getEmail());
        txt_user_phone.setText(account.getPhone());

        Customer customer = new Customer();
        CustomerDAO customerDAO = new CustomerDAO();
        customer = customerDAO.getByAccountID(account.getID());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dob = sdf.format(customer.getDoB());
        txt_user_dob.setText(dob);
        txt_user_address.setText(customer.getAddress());
        
        try {
            BufferedImage img = ImageIO.read(new File(System.getProperty("user.dir") + "\\Images\\User\\" + txt_user_username.getText() + ".png"));
            lbl_user_avatar.setIcon(new ImageIcon(img));
        } catch (Exception e) {
        }
    }
    private static boolean flag1 = false;

    private void btn_user_changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_changePasswordActionPerformed
        // TODO add your handling code here:
        flag1 = !flag1;
        txt_user_password.setEditable(flag1);
        txt_user_confirmPassword.setEditable(flag1);

    }//GEN-LAST:event_btn_user_changePasswordActionPerformed

    private void tbl_invoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_invoiceMouseClicked
        // TODO add your handling code here:
        int index = tbl_invoice.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl_invoice.getModel();
        int invoiceID = (int) model.getValueAt(index, 2);
        lbl_history_no.setText(String.valueOf(invoiceID));
        lbl_history_Date.setText(String.valueOf(model.getValueAt(index, 0)));
        lbl_history_total.setText(String.valueOf(model.getValueAt(index, 1)));
        loadInvoiceDetailsTable(invoiceID);
    }//GEN-LAST:event_tbl_invoiceMouseClicked

    private void btn_user_goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_goBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_user_goBackActionPerformed

    private void btn_user_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_saveActionPerformed
        // TODO add your handling code here:
        user.setFullName(txt_user_fullname.getText());
        user.setEmail(txt_user_email.getText());
        user.setPhone(txt_user_phone.getText());
        user.setAvatar(user.getUsername() + ".jpg");
        AccountDAO accountDAO = new AccountDAO();
        if (accountDAO.update(user)) {
            this.setUser(user);
            Customer customer = new Customer();
            CustomerDAO customerDAO = new CustomerDAO();
            customer = customerDAO.getByAccountID(this.user.getID());
            customer.setAddress(txt_user_address.getText());
            saveImage();
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Date dob = sdf.parse(txt_user_dob.getText());
                customer.setDoB(dob);
            } catch (Exception e) {
            }
            if (customerDAO.update(customer)) {
                JOptionPane.showMessageDialog(this, "Update Successfully!!!");
            } else {
                JOptionPane.showMessageDialog(this, "Update failed!!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Update failed!!!");
        }
    }//GEN-LAST:event_btn_user_saveActionPerformed

    private void btn_user_userpass_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_userpass_saveActionPerformed
        // TODO add your handling code here:
        if (Arrays.equals(txt_user_password.getPassword(), txt_user_confirmPassword.getPassword())) {
            user.setPassword(new String(txt_user_password.getPassword()));
            AccountDAO accountDAO = new AccountDAO();
            if (accountDAO.update(user)) {
                JOptionPane.showMessageDialog(this, "Update Successfully!!!");
            } else {
                JOptionPane.showMessageDialog(this, "Update Failed!!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Password does not match!!!");
        }

    }//GEN-LAST:event_btn_user_userpass_saveActionPerformed

    private void btn_user_chooseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_chooseImgActionPerformed
        // TODO add your handling code here:

        // Ben netbeans khong co khung hien thi image rieng nen ta hien thi image bang cach set ICON cho LABEL
        // Tao Label gom co border nhu binh thuong.
        
        //Filter de chi chon duoc file hinh anh
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG, GIF, and PNG Images", "jpg", "gif", "png");
        imageChooser.setFileFilter(filter);
               
        //lay hinh anh tu file va gan len label
        if (imageChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) { // JFileChooser.APPROVE_OPTION == khi bam OK
            File file = imageChooser.getSelectedFile(); //Lay ra file vua chon
                        
            //Convert file thanh icon
            String filename = file.getAbsolutePath();
            ImageIcon icon = new ImageIcon(filename);
            
            //Scale hinh anh vua voi khung LABEL
            Image image = icon.getImage().getScaledInstance(lbl_user_avatar.getWidth(), lbl_user_avatar.getHeight(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(image);//Gan lai hinh anh vua scale vao lai bien Icon
            
            // set icon cho label
            lbl_user_avatar.setIcon(icon);
        }
    }//GEN-LAST:event_btn_user_chooseImgActionPerformed
private void saveImage() {
        //Tao bien img - kiểu biến là BufferedImage
        BufferedImage img = new BufferedImage(lbl_user_avatar.getIcon().getIconWidth(),  //Chú ý là ta lấy chiều dài + rộng của ICON trên label
                                              lbl_user_avatar.getIcon().getIconHeight(), 
                                              BufferedImage.TYPE_INT_ARGB);
        
        //Tao bien graphic de ve lai hinh anh vao bien img
        //Do tính chất của netbeans nên ta phải làm cách thủ công như vậy
        Graphics2D g2d = img.createGraphics();
        lbl_user_avatar.getIcon().paintIcon(null, g2d, 0, 0);
        g2d.dispose();

        //Tạo đường dẫn để lưu
        //System.getProperty("user.dir") là địa chỉ đến project 
        //sau đó + thêm tùy vào địa chỉ thư mục lưu hình ảnh.
        //cuối cùng + tên file hình. Vd tên.png - txt_product_name.getText() + ".png"
        String location = System.getProperty("user.dir") + "\\Images\\User\\" + txt_user_username.getText() + ".png";

        try {
            //Lưu hình.
            //chú ý: Nên lưu dưới dạng png bởi vì nếu chọn file png mà muốn lưu dưới dạng jpg sẽ bị lỗi. Còn lưu dưới dạng png thì chọn file nào cũng được.
            ImageIO.write(img, "png", new File(location));
        } catch (Exception e) {
            System.out.println("failed");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrm(new Account()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_user_changePassword;
    private javax.swing.JButton btn_user_chooseImg;
    private javax.swing.JButton btn_user_goBack;
    private javax.swing.JButton btn_user_save;
    private javax.swing.JButton btn_user_userpass_save;
    private javax.swing.JFileChooser imageChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_history_Date;
    private javax.swing.JLabel lbl_history_no;
    private javax.swing.JLabel lbl_history_total;
    private javax.swing.JLabel lbl_user_avatar;
    private javax.swing.JTable tbl_invoice;
    private javax.swing.JTable tbl_invoiceDetails;
    private javax.swing.JTextField txt_user_address;
    private javax.swing.JPasswordField txt_user_confirmPassword;
    private javax.swing.JTextField txt_user_dob;
    private javax.swing.JTextField txt_user_email;
    private javax.swing.JTextField txt_user_fullname;
    private javax.swing.JPasswordField txt_user_password;
    private javax.swing.JTextField txt_user_phone;
    private javax.swing.JTextField txt_user_username;
    // End of variables declaration//GEN-END:variables
}
